import React, { useState, useMemo, useCallback } from 'react';
import { X, User, Mail, Phone, Calendar, ChevronDown, Key, Copy, Check, Eye, EyeOff, RefreshCw } from 'lucide-react';

interface AddUserModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (userData: UserFormData) => void;
}

export interface UserFormData {
  firstName: string;
  middleName: string;
  lastName: string;
  dateOfBirth: string;
  cellNumber: string;
  emailAddress: string;
  role: string;
  password: string;
}

const AddUserModal: React.FC<AddUserModalProps> = ({ isOpen, onClose, onSubmit }) => {
  const [formData, setFormData] = useState<UserFormData>({
    firstName: '',
    middleName: '',
    lastName: '',
    dateOfBirth: '',
    cellNumber: '',
    emailAddress: '',
    role: '',
    password: '',
  });

  const [showPassword, setShowPassword] = useState(false);
  const [passwordCopied, setPasswordCopied] = useState(false);
  const [errors, setErrors] = useState<Partial<Record<keyof UserFormData, string>>>({});

  const roles = ['Resident', 'Meter Reader', 'Staff', 'Super Admin'];
  const isAutoGeneratedRole = formData.role === 'Resident' || formData.role === 'Meter Reader';
  const isManualRole = formData.role === 'Staff' || formData.role === 'Super Admin';

  // Parse DOB into components for password generation
  const parseDOB = useCallback((dob: string): { mm: string; dd: string; yyyy: string } | null => {
    const cleaned = dob.replace(/[^0-9]/g, '');
    if (cleaned.length < 6) return null;
    const mm = cleaned.substring(0, 2).padStart(2, '0');
    const dd = cleaned.length >= 4 ? cleaned.substring(2, 4).padStart(2, '0') : '01';
    const yyyy = cleaned.length >= 8 ? cleaned.substring(4, 8) : cleaned.substring(4, 6);
    return { mm, dd, yyyy: yyyy.length === 2 ? `20${yyyy}` : yyyy };
  }, []);

  // Auto-generate temporary password for Resident/Meter Reader
  const autoPassword = useMemo(() => {
    if (!isAutoGeneratedRole || !formData.lastName || !formData.dateOfBirth) return '';
    const dob = parseDOB(formData.dateOfBirth);
    if (!dob) return '';
    return `${formData.lastName.toLowerCase()}_${dob.mm}${dob.dd}${dob.yyyy}`;
  }, [formData.lastName, formData.dateOfBirth, isAutoGeneratedRole, parseDOB]);

  // Generate password for Staff/Super Admin
  const handleGeneratePassword = useCallback(() => {
    const base = formData.lastName.toLowerCase() || 'user';
    const orgSuffix = formData.emailAddress.includes('@bkwb.com') ? 'bkwb' : 'org';
    const year = new Date().getFullYear();
    const randomDigits = Math.floor(10 + Math.random() * 89).toString();
    const generated = `${base}_${orgSuffix}${year}${randomDigits}`;
    setFormData((prev) => ({ ...prev, password: generated }));
  }, [formData.lastName, formData.emailAddress]);

  const handleCopyPassword = () => {
    const pwd = isAutoGeneratedRole ? autoPassword : formData.password;
    if (pwd) {
      navigator.clipboard.writeText(pwd);
      setPasswordCopied(true);
      setTimeout(() => setPasswordCopied(false), 2000);
    }
  };

  const validateForm = () => {
    const newErrors: Partial<Record<keyof UserFormData, string>> = {};

    if (!formData.firstName.trim()) newErrors.firstName = 'First name is required';
    if (!formData.lastName.trim()) newErrors.lastName = 'Last name is required';
    if (!formData.dateOfBirth.trim()) newErrors.dateOfBirth = 'Date of birth is required';
    if (!formData.cellNumber.trim()) newErrors.cellNumber = 'Cell number is required';
    if (!formData.emailAddress.trim()) newErrors.emailAddress = 'Email address is required';
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.emailAddress))
      newErrors.emailAddress = 'Invalid email format';
    if (!formData.role) newErrors.role = 'Role assignment is required';
    if (isManualRole && !formData.password.trim())
      newErrors.password = 'Password is required for this role';
    if (isManualRole && formData.password.trim() && formData.password.length < 8)
      newErrors.password = 'Password must be at least 8 characters';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = () => {
    if (validateForm()) {
      onSubmit({
        ...formData,
        password: isAutoGeneratedRole ? autoPassword : formData.password,
      });
      handleClose();
    }
  };

  const handleClose = () => {
    setFormData({
      firstName: '',
      middleName: '',
      lastName: '',
      dateOfBirth: '',
      cellNumber: '',
      emailAddress: '',
      role: '',
      password: '',
    });
    setErrors({});
    setShowPassword(false);
    setPasswordCopied(false);
    onClose();
  };

  if (!isOpen) return null;

  const formatDateForDisplay = (value: string) => {
    const cleaned = value.replace(/[^0-9]/g, '');
    if (cleaned.length <= 2) return cleaned;
    if (cleaned.length <= 4) return `${cleaned.slice(0, 2)}/${cleaned.slice(2)}`;
    return `${cleaned.slice(0, 2)}/${cleaned.slice(2, 4)}/${cleaned.slice(4, 8)}`;
  };

  const InputField = ({
    label,
    value,
    onChange,
    placeholder,
    icon: Icon,
    error,
    required,
    disabled,
    type = 'text',
  }: {
    label: string;
    value: string;
    onChange: (v: string) => void;
    placeholder?: string;
    icon?: React.FC<{ className?: string }>;
    error?: string;
    required?: boolean;
    disabled?: boolean;
    type?: string;
  }) => (
    <div>
      <label className="block text-xs font-semibold text-gray-700 uppercase mb-2">
        {label}
        {required && <span className="text-red-500 ml-0.5">*</span>}
        {!required && <span className="text-gray-400 font-normal lowercase"> (optional)</span>}
      </label>
      <div className="relative">
        {Icon && (
          <Icon className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
        )}
        <input
          type={type}
          placeholder={placeholder}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          className={`w-full ${Icon ? 'pl-10' : 'px-4'} pr-4 py-2.5 border ${
            error ? 'border-red-300' : 'border-gray-300'
          } rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-sm disabled:bg-gray-50 disabled:text-gray-500`}
        />
      </div>
      {error && <p className="text-xs text-red-600 mt-1">{error}</p>}
    </div>
  );

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl w-full max-w-lg shadow-2xl max-h-[90vh] overflow-y-auto">
        {/* Modal Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between z-10">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Create User</h2>
            <p className="text-xs text-gray-500 mt-1">
              Register a new user account in the system
            </p>
          </div>
          <button
            onClick={handleClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="px-6 py-6 space-y-5">
          {/* Personal Information Section */}
          <div>
            <div className="flex items-center space-x-2 mb-4">
              <div className="w-7 h-7 bg-primary-50 rounded-lg flex items-center justify-center">
                <User className="w-3.5 h-3.5 text-primary-600" />
              </div>
              <h3 className="text-sm font-semibold text-gray-900">Personal Information</h3>
            </div>

            <div className="space-y-4">
              <InputField
                label="First Name"
                value={formData.firstName}
                onChange={(v) => setFormData({ ...formData, firstName: v })}
                placeholder="e.g. Juan"
                icon={User}
                error={errors.firstName}
                required
              />

              <InputField
                label="Middle Name"
                value={formData.middleName}
                onChange={(v) => setFormData({ ...formData, middleName: v })}
                placeholder="e.g. Reyes"
              />

              <InputField
                label="Last Name"
                value={formData.lastName}
                onChange={(v) => setFormData({ ...formData, lastName: v })}
                placeholder="e.g. Dela Cruz"
                icon={User}
                error={errors.lastName}
                required
              />

              <InputField
                label="Date of Birth"
                value={formData.dateOfBirth}
                onChange={(v) => setFormData({ ...formData, dateOfBirth: formatDateForDisplay(v) })}
                placeholder="MM/DD/YYYY"
                icon={Calendar}
                error={errors.dateOfBirth}
                required
              />

              <InputField
                label="Cell Number"
                value={formData.cellNumber}
                onChange={(v) => setFormData({ ...formData, cellNumber: v })}
                placeholder="+63 9XX XXX XXXX"
                icon={Phone}
                error={errors.cellNumber}
                required
              />

              <InputField
                label="Email Address"
                value={formData.emailAddress}
                onChange={(v) => setFormData({ ...formData, emailAddress: v })}
                placeholder={isManualRole ? 'user@bkwb.com' : 'user@email.com'}
                icon={Mail}
                error={errors.emailAddress}
                required
              />
            </div>
          </div>

          {/* Role Assignment Section */}
          <div>
            <label className="block text-xs font-semibold text-gray-700 uppercase mb-2">
              Role Assignment <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <select
                value={formData.role}
                onChange={(e) => setFormData({ ...formData, role: e.target.value, password: '' })}
                className={`w-full px-4 py-2.5 border ${
                  errors.role ? 'border-red-300' : 'border-gray-300'
                } rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-sm appearance-none bg-white`}
              >
                <option value="">Select a role...</option>
                {roles.map((role) => (
                  <option key={role} value={role}>{role}</option>
                ))}
              </select>
              <ChevronDown className="absolute right-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
            </div>
            {errors.role && <p className="text-xs text-red-600 mt-1">{errors.role}</p>}
          </div>

          {/* Password Section */}
          {formData.role && (
            <div className="bg-gray-50 rounded-xl p-4 border border-gray-200">
              <div className="flex items-center space-x-2 mb-3">
                <Key className="w-4 h-4 text-gray-500" />
                <h3 className="text-sm font-semibold text-gray-700">
                  {isAutoGeneratedRole ? 'Auto-Generated Password' : 'Set Password'}
                </h3>
              </div>

              {isAutoGeneratedRole && (
                <>
                  <div className="bg-white border border-gray-200 rounded-lg p-3 mb-2">
                    <div className="flex items-center justify-between">
                      <code className="text-sm font-mono font-bold text-primary-700">
                        {autoPassword || (
                          <span className="text-gray-400 italic">
                            Fill in last name and date of birth
                          </span>
                        )}
                      </code>
                      {autoPassword && (
                        <button
                          onClick={handleCopyPassword}
                          className="p-1.5 text-gray-400 hover:text-primary-600 hover:bg-primary-50 rounded transition-all"
                          title="Copy password"
                        >
                          {passwordCopied ? (
                            <Check className="w-4 h-4 text-green-500" />
                          ) : (
                            <Copy className="w-4 h-4" />
                          )}
                        </button>
                      )}
                    </div>
                  </div>
                  <div className="flex items-start space-x-2 text-xs text-gray-500">
                    <div className="w-1 h-1 bg-gray-400 rounded-full mt-1.5 flex-shrink-0" />
                    <p>
                      Temporary password format: <strong>lastname_MMDDYYYY</strong>
                    </p>
                  </div>
                  <div className="mt-2 px-3 py-2 bg-blue-50 border border-blue-200 rounded-lg">
                    <p className="text-xs text-blue-700">
                      <strong>Note:</strong> This temporary password will be provided to the user
                      and should be changed after their first login.
                    </p>
                  </div>
                </>
              )}

              {isManualRole && (
                <>
                  <div className="relative">
                    <input
                      type={showPassword ? 'text' : 'password'}
                      placeholder="Enter password (min. 8 characters)"
                      value={formData.password}
                      onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                      className={`w-full px-4 pr-24 py-2.5 border ${
                        errors.password ? 'border-red-300' : 'border-gray-300'
                      } rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-sm`}
                    />
                    <div className="absolute right-1 top-1/2 transform -translate-y-1/2 flex items-center space-x-0.5">
                      <button
                        type="button"
                        onClick={handleGeneratePassword}
                        className="p-1.5 text-gray-400 hover:text-primary-600 hover:bg-primary-50 rounded transition-colors"
                        tabIndex={-1}
                        title="Generate password"
                      >
                        <RefreshCw className="w-4 h-4" />
                      </button>
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="p-1.5 text-gray-400 hover:text-gray-600 rounded transition-colors"
                        tabIndex={-1}
                      >
                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                      <button
                        type="button"
                        onClick={handleCopyPassword}
                        className="p-1.5 text-gray-400 hover:text-primary-600 rounded transition-colors"
                        tabIndex={-1}
                        title="Copy password"
                      >
                        {passwordCopied ? (
                          <Check className="w-4 h-4 text-green-500" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                      </button>
                    </div>
                  </div>
                  {errors.password && <p className="text-xs text-red-600 mt-1">{errors.password}</p>}
                  <p className="text-xs text-gray-500 mt-1">
                    Use organization credentials (e.g., <strong>@bkwb.com</strong>).
                    Click <RefreshCw className="w-3 h-3 inline-block" /> to auto-generate.
                  </p>
                </>
              )}
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="sticky bottom-0 bg-gray-50 border-t border-gray-200 px-6 py-4 flex items-center justify-end space-x-3 rounded-b-2xl">
          <button
            onClick={handleClose}
            className="px-5 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            className="px-5 py-2 text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 rounded-lg transition-colors"
          >
            Create User
          </button>
        </div>
      </div>
    </div>
  );
};

export default AddUserModal;
